language: php
php:
- '5.5'
- '5.4'
services:
- postgresql
- rabbitmq
env:
  global:
  - ENVIRONMENT=testing
  - LIBRETIME_LOG_DIR=/tmp/log/libretime
install:
- composer install
- pip install --user mkdocs 
before_script:
- psql -c 'CREATE DATABASE libretime;' -U postgres
- psql -c "CREATE USER libretime WITH PASSWORD 'libretime';" -U postgres
- psql -c 'GRANT CONNECT ON DATABASE libretime TO libretime;' -U postgres
- psql -c 'ALTER USER libretime CREATEDB;' -U postgres
- mkdir -p /tmp/log/libretime
script:
- pushd airtime_mvc/tests && ../../vendor/bin/phpunit && popd
- mkdocs build --clean -q > /dev/null
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/docs
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  repo: LibreTime/LibreTime.github.io
  project_name: LibreTime
  fqdn: libretime.org
  name: R. LibreTime DocBot
  on:
    branch: master
